### ISSUE TITLE
running parallel filter actions

### ISSUE THREAD

**Issue by thalesvon** [actions/bin#62] opened 2019-07-22 17:05 UTC
Hey guys, I am implementing my pipeline with github actions and the filter action is just amazing. 
I wanted to write my entire pipeline (dev qa and production) using the same workflow, as they are very similar and I wanted to reuse some action, so here is a picture of what I wanted to build:
![image](https://user-images.githubusercontent.com/19493900/61650360-ed1b5800-ac89-11e9-8b6c-82c28e39c8ed.png)

Here are the filter actions I have on my `main.workflow`:

```
....
action "Push on Master" {
  needs = "Build solution"
  uses = "actions/bin/filter@master"
  args = "branch master"
}

action "Push on Release branch" {
  needs = "Build solution"
  uses = "actions/bin/filter@master"
  args = "branch release/*"
}

action "New Tag Created" {
  needs = "Build solution"
  uses = "actions/bin/filter@master"
  args = "tag v*"
}
...
```

As the expected result, on a push event, which is what my workflow listens to, I thought I would get two of these actions resulting in Neutral status and one would Succeed and keep the workflow going. But as you can see in the picture I got, 1 Neutral and the other two Cancelled.

Here is the log for the action resulting in Cancelled: 
```
Successfully tagged gcr.io/gct-12-4hwco8ichd5ki6gddiz4ica/2e035e5fb8ad977ee790ec390dcc01678860173c8af763469ce9edd9953e17f2/0c0528c9cdfbbd04f6b09b464de94fce116e820f638af7674f4ac129bf3d799a:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
refs/heads/release/new-ci does not match refs/tags/venv
Action `New Tag Created' cancelled because action `Push on Master' failed

```

And here is the log for the action resulting in Neutral: 
```
Successfully tagged gcr.io/gct-12-4hwco8ichd5ki6gddiz4ica/2e035e5fb8ad977ee790ec390dcc01678860173c8af763469ce9edd9953e17f2/0c0528c9cdfbbd04f6b09b464de94fce116e820f638af7674f4ac129bf3d799a:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
refs/heads/release/new-ci does not match refs/heads/master

### DECLINED Push on Master 16:48:36Z (21.319s)
```

My event was a push on release/*, my question here is: Is there a way to use multiple filter action parallel?
I don't quite understand why parallel actions depend on each other result to run, I mean, they are supposed to be parallel, in this case running in different containers, right?

**Comment by thedarkwriter** [comment] 2019-07-24 16:16
I had the same desire and got this to work by creating two workflows with essentially duplicate actions. They will both execute but one (or both) will go neutral and the other will succeed.

**Comment by fnkr** [comment] 2019-08-09 16:06
I think this is a duplicate of #34.

**Comment by chrispat** [comment] 2019-09-26 00:57
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions

**Closed by chrispat** 2019-09-26 00:57 UTC
